apiVersion: v1
kind: Pod
metadata:
  name: gpupod
spec:
  containers:
  - name: my-gpu-container
    image: nvidia/cuda:10.0-devel-ubuntu18.04
    command: ["sleep", "infinity"]
    resources:
      limits:
       nvidia.com/gpu: 1
  tolerations:
  - key: special
    operator: "Equal"
    value: gpu
    effect: "NoSchedule"
  - key: nvidia.com/gpu
    operator: "Equal"
    value: present
    effect: "NoSchedule"
  nodeSelector:
    cloud.google.com/gke-nodepool: pool-gpu
